name: wethr
version: git
summary: Command line weather tool.
description: |
  Get current weather:-
    $ wethr
  Get current weather in metric units
    $ wethr --metric
  Get current weather in imperial units
    $ wethr --imperial

grade: devel
confinement: devmode

apps:
  wethr:
    command: wethr

parts:
  wethr:
    plugin: nodejs
    source: .
