name: wethr
version: git
summary: Command line weather tool.
description: |

grade: stable
confinement: strict

apps:
  wethr:
    command: wethr
    plugs:
      - network

parts:
  wethr:
    plugin: nodejs
    source: https://github.com/twobucks/wethr.git
